### ISSUE TITLE
Deep linking

### ISSUE THREAD

**Issue by davidsalamon** [cloudstorm/cloudstorm#41]
CS-Menu (component), which, if added to template, shows bootstrap menu at the top of screen, listing the registered modules iwht links to resource index pages

Main goal: 
Index page should be accessible via url
Edit "page" should be accessible via url
New page should be accessible via url

Direct link (url/{resource}/{id}/show) should open page of resource

use https://ui-router.github.io/

Optional: Create Show page for item
* List all attributes and values
* In descriptor: create facility to hide attributes on show page only
* Make list items auto linked in CSIndex
NOTE: see CSForm for inspiration or reuse

**Comment by davidsalamon** [comment]
Pre requisite: sort out permanent urls / show page

**Comment by kdaveed** [comment]
1.
Pattern:
http://localhost:8000/sample.html/#/{resourceName}
Using:
https://ui-router.github.io/

2.
http://localhost:8000/sample.html/#/{resourceName}/{id}
![screen shot 2017-08-21 at 17 13 17](https://user-images.githubusercontent.com/7580884/29525786-14a48586-8694-11e7-899e-b9a7e693e352.png)

**Comment by kdaveed** [comment]
3.
http://localhost:8000/sample.html/#/{resourceName}/5/{show/edit}
4.
http://localhost:8000/sample.html/#/{resourceName}/{create}

**Comment by kdaveed** [comment]
* provider hides ui-router from cs-index.
* cs-index --> provider --> ui-rooter

**Comment by kdaveed** [comment]
I would suggest the following specification change: 

**Change edit and show links**

I. Instead of placing the show button into each row, there should be an edit button:

![screen shot 2017-10-09 at 13 41 45](https://user-images.githubusercontent.com/7580884/31336542-9cf68c7a-acf7-11e7-973d-70919966cff8.png)

The clicking this edit button would lead to the edit state:

To this state the following URL pattern belongs: 
http://localhost:8000/sample.html/#/{resourceName}/{id}/edit

II. The clicking simply on the row of the data entry calls the data page:

![screen shot 2017-10-09 at 13 51 55](https://user-images.githubusercontent.com/7580884/31336859-0dbf60d4-acf9-11e7-8e31-8e84f1dc1b2f.png)

URL Pattern:
http://localhost:8000/sample.html/#/{resourceName}/{id}
